name: build

on:
  push:
    branches:
      main

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GO_VERSION: "^1.21"
  
jobs:

  build-android1:
    runs-on: ubuntu-latest
    env:
      tag: alpha
    steps:
      - name: Build
        env:
          VERSION: ${{ env.tag }}
        run: |
          echo ${{ env.VERSION }}
